spring:
  data:
    mongodb:
      host: localhost
      database: StarTourDatabase
      port: 27017
      username: anas
      password: root123
      authentication-database: admin
telegram:
  bot:
    token: 6773325600:AAEqx28Tc4QduN9MG6JR1EIlve5Xdw0luZU