spring:
  data:
    mongodb:
      host: your_host
      database: your_db
      port: 27017
      username: your_db_username
      password: your_db_password
      authentication-database: db_for_auth
telegram:
  bot:
    token: your_tg_bot_token